def create_manager
  manager = create_user(User::USER_TYPE_MANAGER)
  5.times do |i|
    create_user(User::USER_TYPE_CLIENT, manager)
  end
  manager
end


def create_user(type, owner = nil)
  User.create(
     :user_type => type,
     :login => Faker::Internet.user_name,
     :name => Faker::Name.name,
     :password => Digest::MD5.hexdigest('admin'),
     :email => Faker::Internet.email,
     :phone => Faker::PhoneNumber.phone_number,
     :phone_mobile => Faker::PhoneNumber.phone_number,
     :owner => owner
  )
end


admin = User.create({:user_type => User::USER_TYPE_ADMIN, :login => 'admin', :password => Digest::MD5.hexdigest('admin'), :email => 'krasilnikov.ilya@gmail.com'})
5.times do |i|
  create_user(User::USER_TYPE_CLIENT, admin)
end



Material.create({:name => 'баннер блэкаут'})
Material.create({:name => 'баннер литой '})
Material.create({:name => 'баннер транслюцентный'})
Material.create({:name => 'баннер транслюцентный'})
Material.create({:name => 'баннер фронтлит'})
Material.create({:name => 'брелок'})
Material.create({:name => 'бумага Блюбак'})
Material.create({:name => 'бумага газетная'})
Material.create({:name => 'бумага для скролера'})
Material.create({:name => 'бумага для сольвентной печати'})
Material.create({:name => 'бумага для струйной печати'})
Material.create({:name => 'бумага самоклеющаяся'})
Material.create({:name => 'бумага ситилайт'})
Material.create({:name => 'дизайнерская бумага'})
Material.create({:name => 'диск ДВД для печати '})
Material.create({:name => 'диск СД для печати'})
Material.create({:name => 'калька'})
Material.create({:name => 'картон двухстороннего мелования'})
Material.create({:name => 'картон одностороннего мелования'})
Material.create({:name => 'композит'})
Material.create({:name => 'конверт'})
Material.create({:name => 'кружка'})
Material.create({:name => 'материал заказчика'})
Material.create({:name => 'мелованная бумага'})
Material.create({:name => 'офсетная бумага'})
Material.create({:name => 'пакет ПВД'})
Material.create({:name => 'пакет ПНД'})
Material.create({:name => 'пенокартон'})
Material.create({:name => 'пластик ПВХ'})
Material.create({:name => 'пленка Бэклит'})
Material.create({:name => 'пленка Бэклит реверсивный'})
Material.create({:name => 'пленка виниловая без клеевого слоя'})
Material.create({:name => 'пленка виниловая самоклеющаяся'})
Material.create({:name => 'пленка для ламинирования'})
Material.create({:name => 'пленка полипропиленовая'})
Material.create({:name => 'пленка ПЭТ'})
Material.create({:name => 'плитка керамическая'})
Material.create({:name => 'поликарбонат сотовый'})
Material.create({:name => 'ручка шариковая'})
Material.create({:name => 'сетка баннерная без подложки'})
Material.create({:name => 'сетка баннерная с подложкой'})
Material.create({:name => 'стекло'})
Material.create({:name => 'стекло акриловое'})
Material.create({:name => 'ткань полиэстер'})
Material.create({:name => 'ткань сатин'})
Material.create({:name => 'ткань флаговая'})
Material.create({:name => 'флизелин для фотообоев'})
Material.create({:name => 'фольга'})
Material.create({:name => 'холст искусственный'})
Material.create({:name => 'холст натуральный'})


ProductType.create({:name => 'абанемент'})
ProductType.create({:name => 'анкета'})
ProductType.create({:name => 'афиша'})
ProductType.create({:name => 'банкноты'})
ProductType.create({:name => 'баннер'})
ProductType.create({:name => 'бейджи'})
ProductType.create({:name => 'бейсболки'})
ProductType.create({:name => 'билет'})
ProductType.create({:name => 'билеты'})
ProductType.create({:name => 'бирки'})
ProductType.create({:name => 'бланк'})
ProductType.create({:name => 'блокнот'})
ProductType.create({:name => 'брелок'})
ProductType.create({:name => 'брендбук'})
ProductType.create({:name => 'брошюра'})
ProductType.create({:name => 'Буклеты'})
ProductType.create({:name => 'бумажные пакеты'})
ProductType.create({:name => 'визитки'})
ProductType.create({:name => 'Визитки'})
ProductType.create({:name => 'визитки термоподьем'})
ProductType.create({:name => 'вкладыши'})
ProductType.create({:name => 'воблеры'})
ProductType.create({:name => 'вывеска'})
ProductType.create({:name => 'вышивка на бейсболке'})
ProductType.create({:name => 'гравировка'})
ProductType.create({:name => 'грамота'})
ProductType.create({:name => 'диплом'})
ProductType.create({:name => 'диски'})
ProductType.create({:name => 'дисконтные карты'})
ProductType.create({:name => 'документация'})
ProductType.create({:name => 'ежедневники'})
ProductType.create({:name => 'журнал'})
ProductType.create({:name => 'закладка'})
ProductType.create({:name => 'заявки'})
ProductType.create({:name => 'календари'})
ProductType.create({:name => 'календари домик'})
ProductType.create({:name => 'календари карманные'})
ProductType.create({:name => 'календарь квартальный на 1 х пружинах 1 рекламное поле'})
ProductType.create({:name => 'календарь квартальный на 3 х пружинах 1 рекламное поле'})
ProductType.create({:name => 'календарь квартальный на 3 х пружинах 3 рекламных поля'})
ProductType.create({:name => 'календарь настенный'})
ProductType.create({:name => 'календарь перекидной'})
ProductType.create({:name => 'картина'})
ProductType.create({:name => 'Каталог'})
ProductType.create({:name => 'книга'})
ProductType.create({:name => 'конверты'})
ProductType.create({:name => 'Конверты'})
ProductType.create({:name => 'копирование'})
ProductType.create({:name => 'коробочки'})
ProductType.create({:name => 'круги'})
ProductType.create({:name => 'кружки с нанесением'})
ProductType.create({:name => 'ксерокопии'})
ProductType.create({:name => 'кубарики'})
ProductType.create({:name => 'купоны'})
ProductType.create({:name => 'листовая продукция'})
ProductType.create({:name => 'листовка'})
ProductType.create({:name => 'Листовки'})
ProductType.create({:name => 'лифлет'})
ProductType.create({:name => 'лотерейные билеты'})
ProductType.create({:name => 'макет'})
ProductType.create({:name => 'медиакит'})
ProductType.create({:name => 'Меню'})
ProductType.create({:name => 'мобайл'})
ProductType.create({:name => 'мобильный стенд'})
ProductType.create({:name => 'наклейки '})
ProductType.create({:name => 'наклейки с насечками'})
ProductType.create({:name => 'наклейки с персонализацией'})
ProductType.create({:name => 'нанесение на скотч'})
ProductType.create({:name => 'новогодние шары'})
ProductType.create({:name => 'номера'})
ProductType.create({:name => 'обложка'})
ProductType.create({:name => 'открытка'})
ProductType.create({:name => 'Открытки'})
ProductType.create({:name => 'пакеты'})
ProductType.create({:name => 'пакеты бумажные '})
ProductType.create({:name => 'пакеты ПВД'})
ProductType.create({:name => 'пакеты смесовые'})
ProductType.create({:name => 'панель'})
ProductType.create({:name => 'папки'})
ProductType.create({:name => 'Папки'})
ProductType.create({:name => 'папки вырубные'})
ProductType.create({:name => 'папки с вырубным окошком'})
ProductType.create({:name => 'папки с клеевым карманом'})
ProductType.create({:name => 'пенокартон'})
ProductType.create({:name => 'перетяжка'})
ProductType.create({:name => 'плакат'})
ProductType.create({:name => 'планшет'})
ProductType.create({:name => 'пластиковые карты'})
ProductType.create({:name => 'пластиковые номерки'})
ProductType.create({:name => 'пленка'})
ProductType.create({:name => 'плитка'})
ProductType.create({:name => 'плотерная резка'})
ProductType.create({:name => 'подарочный сертификат'})
ProductType.create({:name => 'постер  '})
ProductType.create({:name => 'Постеры'})
ProductType.create({:name => 'прайс-листы'})
ProductType.create({:name => 'презентeр'})
ProductType.create({:name => 'презентация'})
ProductType.create({:name => 'приглашения с персонализацией'})
ProductType.create({:name => 'пропуска'})
ProductType.create({:name => 'роллер'})
ProductType.create({:name => 'рубашки поло'})
ProductType.create({:name => 'ручки'})
ProductType.create({:name => 'СD'})
ProductType.create({:name => 'световой короб'})
ProductType.create({:name => 'световой короб'})
ProductType.create({:name => 'сертификаты'})
ProductType.create({:name => 'сканирование слайдов'})
ProductType.create({:name => 'стикер'})
ProductType.create({:name => 'Стикеры'})
ProductType.create({:name => 'табличка'})
ProductType.create({:name => 'талоны'})
ProductType.create({:name => 'термонаклейки'})
ProductType.create({:name => 'тиражирование'})
ProductType.create({:name => 'тиснение на папках'})
ProductType.create({:name => 'удостоверения на скрепку'})
ProductType.create({:name => 'фирменные бланки'})
ProductType.create({:name => 'флаг'})
ProductType.create({:name => 'флаер'})
ProductType.create({:name => 'фотообои'})
ProductType.create({:name => 'фотопанели'})
ProductType.create({:name => 'фотопотолок'})
ProductType.create({:name => 'фризы'})
ProductType.create({:name => 'Футболки'})
ProductType.create({:name => 'цветопроба'})
ProductType.create({:name => 'ценники'})
ProductType.create({:name => 'штамп'})
ProductType.create({:name => 'штендер '})
ProductType.create({:name => 'этикетки'})


PrintMethod.create({:name => 'ризограф'})
PrintMethod.create({:name => 'офсет А3'})
PrintMethod.create({:name => 'офсет А2'})
PrintMethod.create({:name => 'офсет А1'})
PrintMethod.create({:name => 'офсет А0'})
PrintMethod.create({:name => 'офсет роль'})
PrintMethod.create({:name => 'цифровая печать HP 3200'})
PrintMethod.create({:name => 'цифровая печать DС50'})
PrintMethod.create({:name => 'цифровая печать DС250'})
PrintMethod.create({:name => 'цифровая печать 7000'})
PrintMethod.create({:name => 'цифровая печать ИНДИГО'})
PrintMethod.create({:name => 'фольгирование'})
PrintMethod.create({:name => 'флексопечать'})
PrintMethod.create({:name => 'тампопечать'})
PrintMethod.create({:name => 'шелкография'})
PrintMethod.create({:name => 'тиснение'})
PrintMethod.create({:name => 'тиснение конгревное'})
PrintMethod.create({:name => 'лакировка'})
PrintMethod.create({:name => 'уф лак'})
PrintMethod.create({:name => 'вд лак'})
PrintMethod.create({:name => 'интерьерная печать ОСЕ 720'})
PrintMethod.create({:name => 'интерьерная печать ОСЕ 1200'})
PrintMethod.create({:name => 'интерьерная печать ОСЕ 1440'})
PrintMethod.create({:name => 'широкоформатная печать MyJet 240'})
PrintMethod.create({:name => 'широкоформатная печать MyJet 360'})
PrintMethod.create({:name => 'широкоформатная печать MyJet 540'})
PrintMethod.create({:name => 'широкоформатная печать MyJet 720'})
PrintMethod.create({:name => 'интерьерная печать Nkad 600'})
PrintMethod.create({:name => 'интерьерная печать Roland 720'})
PrintMethod.create({:name => 'интерьерная печать Mimaki 720'})
PrintMethod.create({:name => 'интерьерная печать Roland 1440'})
PrintMethod.create({:name => 'интерьерная печать Mimaki 1440'})
PrintMethod.create({:name => 'интерьерная прямая печать UF Agfa 720'})
PrintMethod.create({:name => 'интерьерная прямая печать UF Agfa1440'})
PrintMethod.create({:name => 'каттер SP 1360'})
PrintMethod.create({:name => 'Canon 4500'})
PrintMethod.create({:name => 'широкоформатный ламинатор SE'})

#%w{Звонок Письмо email Посылка Рассылка Факс Личная встреча Презентация Выставить счет Доставка Поручение}.map do |i|
#  Taskaction.create({:aname => i})
#end

10.times do |i|
  create_manager
end

[User::USER_TYPE_DESIGNER, User::USER_TYPE_PRINTER, User::USER_TYPE_BG, User::USER_TYPE_LG].each do |type|
  3.times do
    create_user(type)
  end
end

